artifact_location: file:///D:/EUR_AI_MASTER_PROJECTS/Pricing_Model_g/MlFlow_Tracking/749234459119020306
creation_time: 1745810049877
experiment_id: '749234459119020306'
last_update_time: 1745810049877
lifecycle_stage: active
name: PricePredictionExperiment
