channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=25.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - defusedxml==0.7.1
  - ipywidgets==8.1.6
  - matplotlib==3.10.0
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - seaborn==0.13.2
  - statsmodels==0.14.4
name: mlflow-env
