artifact_uri: file:///D:/EUR_AI_MASTER_PROJECTS/Pricing_Model_g/MlFlow_Tracking/749234459119020306/7fe7d18ef8a44bcbbf8e2b7ccd0f424a/artifacts
end_time: 1745810189458
entry_point_name: ''
experiment_id: '749234459119020306'
lifecycle_stage: active
run_id: 7fe7d18ef8a44bcbbf8e2b7ccd0f424a
run_name: dashing-gnu-456
run_uuid: 7fe7d18ef8a44bcbbf8e2b7ccd0f424a
source_name: ''
source_type: 4
source_version: ''
start_time: 1745810050796
status: 3
tags: []
user_id: Ahamadulla_Shaik
