artifact_uri: file:///D:/EUR_AI_MASTER_PROJECTS/Pricing_Model_g/MlFlow_Tracking/749234459119020306/cf9bc5f7eab54a7c98e4a67c27ac3aea/artifacts
end_time: 1745810189782
entry_point_name: ''
experiment_id: '749234459119020306'
lifecycle_stage: active
run_id: cf9bc5f7eab54a7c98e4a67c27ac3aea
run_name: orderly-cub-456
run_uuid: cf9bc5f7eab54a7c98e4a67c27ac3aea
source_name: ''
source_type: 4
source_version: ''
start_time: 1745810189686
status: 3
tags: []
user_id: Ahamadulla_Shaik
