artifact_location: file:///D:/EUR_AI_MASTER_PROJECTS/Pricing_Model_g/MlFlow_Tracking/0
creation_time: 1745810049809
experiment_id: '0'
last_update_time: 1745810049809
lifecycle_stage: active
name: Default
